import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import type { PowerSyncDatabase } from "@powersync/web";
import type { DataServices } from "../../src/data/DataServicesContext.ts";
import { ACCOUNT_SETUP_VERSION, readAccountBinding, writeAccountBinding } from "../../src/data/account/accountBinding.ts";
import { AdoptionConflictError, adoptCanonicalLocalData } from "../../src/data/account/adoptLocalData.ts";
import { authenticatedLifeOSPowerSyncSchema } from "../../src/data/database/authenticatedLifeOSPowerSync.ts";
import { createDefaultNotificationState } from "../../src/data/notifications/localStorageNotificationStateRepository.ts";

const userA="11111111-1111-4111-8111-111111111111",userB="22222222-2222-4222-8222-222222222222";
function bindingDatabase(){let row:Record<string,unknown>|null=null;return{database:{init:async()=>undefined,getOptional:async()=>row,execute:async(_sql:string,args:unknown[])=>{row={user_hash:args[0],setup_choice:args[1],adoption_version:args[2],completed_at:args[3]};}} as unknown as PowerSyncDatabase,get:()=>row};}
function services(seed:{tasks?:unknown[];execution?:unknown[]}={}){let tasks=structuredClone(seed.tasks??[]),execution=structuredClone(seed.execution??[]);const planning={lifeGoals:[],monthlyOutcomes:[],weeklyFocuses:[]},habits={habits:[],completions:[]},notifications=createDefaultNotificationState();let taskWrites=0,executionWrites=0;const value={taskRepository:{initialize:async()=>structuredClone(tasks),replace:async(next:unknown[])=>{taskWrites++;tasks=structuredClone(next);},subscribe:()=>()=>undefined},planningRepository:{initialize:async()=>planning,replace:async()=>undefined,subscribe:()=>()=>undefined},habitRepository:{initialize:async()=>habits,replace:async()=>undefined,subscribe:()=>()=>undefined},executionHistoryRepository:{initialize:async()=>structuredClone(execution),replace:async(next:unknown[])=>{executionWrites++;execution=structuredClone(next);return structuredClone(execution);},append:async()=>structuredClone(execution),remove:async()=>structuredClone(execution),clear:async()=>undefined,subscribe:()=>()=>undefined},profileRepository:{initialize:async()=>null,replace:async(value:unknown)=>value,subscribe:()=>()=>undefined},captureRepository:{initialize:async()=>[],insert:async()=>undefined,delete:async()=>undefined,subscribe:()=>()=>undefined},atlasMemoryRepository:{initialize:async()=>[],getPersistenceState:()=>({phase:"hydrated",error:null}),load:()=>[],save:()=>undefined,clear:()=>undefined,subscribe:()=>()=>undefined},notificationStateRepository:{initialize:async()=>notifications,getPersistenceState:()=>({phase:"hydrated",error:null}),load:()=>notifications,save:()=>undefined,clear:()=>undefined,subscribe:()=>()=>undefined}} as unknown as DataServices;return{value,get taskWrites(){return taskWrites;},get executionWrites(){return executionWrites;}};}
function adoptionDatabase(){let journal:Record<string,unknown>|null=null;return{init:async()=>undefined,getOptional:async()=>journal,execute:async(sql:string,args:unknown[]=[])=>{if(sql.startsWith("INSERT INTO adoption_journal"))journal={user_hash:args[0],adoption_version:args[1],source_hashes_json:args[2],completed_domains_json:args[3],started_at:args[4],updated_at:args[5]};if(sql.startsWith("UPDATE adoption_journal")&&journal)journal={...journal,completed_domains_json:args[0],updated_at:args[1]};if(sql.startsWith("DELETE FROM adoption_journal"))journal=null;},get:async()=>({mem:0,notice:0}),getUploadQueueStats:async()=>({count:0})} as unknown as PowerSyncDatabase;}

test("account binding is user-scoped, versioned, and idempotent",async()=>{const fake=bindingDatabase();assert.equal(await readAccountBinding(fake.database,userA),null);const first=await writeAccountBinding(fake.database,userA,"use-cloud","2026-09-16T00:00:00.000Z");assert.equal(first.version,ACCOUNT_SETUP_VERSION);assert.equal((await writeAccountBinding(fake.database,userA,"use-cloud")).completedAt,first.completedAt);await assert.rejects(()=>readAccountBinding(fake.database,userB),/does not belong/);});
test("adoption copies only empty cloud domains and preserves duplicate execution IDs",async()=>{const duplicate=[{id:7,type:"system",entityId:"x",title:"one",description:"",createdAt:"2026-09-16T00:00:00.000Z",xpAwarded:0},{id:7,type:"system",entityId:"x",title:"two",description:"",createdAt:"2026-09-16T00:00:01.000Z",xpAwarded:0}];const local=services({tasks:[{id:1,title:"local"}],execution:duplicate}),cloud=services();const result=await adoptCanonicalLocalData(local.value,cloud.value,adoptionDatabase(),userA);assert.deepEqual(result.adoptedDomains,["tasks","execution"]);assert.equal(cloud.taskWrites,1);assert.equal(cloud.executionWrites,1);assert.equal((await cloud.value.executionHistoryRepository.initialize()).length,2);});
test("adoption is idempotent for identical data and stops on conflicts",async()=>{const task=[{id:1,title:"same"}];const local=services({tasks:task}),sameCloud=services({tasks:task});assert.deepEqual((await adoptCanonicalLocalData(local.value,sameCloud.value,adoptionDatabase(),userA)).adoptedDomains,[]);assert.equal(sameCloud.taskWrites,0);const conflict=services({tasks:[{id:2,title:"cloud"}]});await assert.rejects(()=>adoptCanonicalLocalData(local.value,conflict.value,adoptionDatabase(),userA),(error:unknown)=>error instanceof AdoptionConflictError&&error.domains.includes("tasks"));});
test("authenticated schema keeps account binding and recovery journal local-only",()=>{for(const name of ["account_binding","adoption_journal"]){const table=authenticatedLifeOSPowerSyncSchema.tables.find(item=>item.name===name);assert.ok(table);assert.equal(table.localOnly,true);}});
test("first-login UI exposes setup and non-destructive conflict choices",()=>{const source=readFileSync(new URL("../../src/components/auth/AuthDataBoundary.tsx",import.meta.url),"utf8");assert.match(source,/Adopt this device’s data into this account/);assert.match(source,/Use existing cloud data/);assert.match(source,/Cancel sign-in setup/);assert.match(source,/Automatic adoption cannot continue safely/);assert.match(source,/Keep device data and cancel setup/);assert.doesNotMatch(source,/replace cloud/i);});
test("canonical hydration reconfigures Execution History inside the provider effect",()=>{const source=readFileSync(new URL("../../src/data/DataServicesContext.tsx",import.meta.url),"utf8");const effect=source.slice(source.indexOf("useEffect(() => {",source.indexOf("export function DataServicesProvider")));assert.ok(effect.indexOf("ExecutionHistoryService.configureRepository")>=0);assert.ok(effect.indexOf("ExecutionHistoryService.configureRepository")<effect.indexOf("ExecutionHistoryService.initialize"));});
