import test from "node:test";
import assert from "node:assert/strict";
import { attentionCategories, attentionWeek, buildAttentionReport, trackingCoverage, validateAllocation, type AttentionSource, type IntendedAllocation } from "../../src/insights/attentionLedger.ts";
import { attentionStorageKey, readAttentionPreferences, saveAttentionPreferences } from "../../src/insights/attentionPreferences.ts";
import { buildFocusCompletionRecord } from "../../src/focus/focusAudit.ts";
import { createFocusSession } from "../../src/focus/focusSession.ts";
import { readFileSync } from "node:fs";

const now = new Date(2026,9,7,18);
const iso = (hour:number,minute=0)=>new Date(2026,9,6,hour,minute).toISOString();
function source(): AttentionSource {
  return {lifeGoals:[1,2].map(id=>({id,title:`Goal ${id}`,progress:0,completed:false,startDate:"2026-10-05",createdAt:iso(8)})),monthlyTargets:[1,2].map(id=>({id,goalId:id,title:`Month ${id}`,month:10,year:2026,progress:0,completed:false,createdAt:iso(8)})),weeklyTargets:[1,2].map(id=>({id,monthlyTargetId:id,title:`Week ${id}`,week:1,progress:0,completed:false,createdAt:iso(8)})),tasks:[1,2].map(id=>({id,weeklyTargetId:id,title:`Task ${id}`,priority:"medium",completed:false,createdAt:iso(8)})),executionRecords:[]};
}
function focus(taskId:number,start:number,end:number,id=taskId) { return buildFocusCompletionRecord(createFocusSession(taskId,"test-account",iso(start),`session-${id}`),iso(end),id); }
const allocation: IntendedAllocation = {version:1,updatedAt:iso(8),shares:[{categoryId:"goal:1",percent:60},{categoryId:"goal:2",percent:40}]};
function measured() {const state=source();state.executionRecords=[buildFocusCompletionRecord(createFocusSession(1,"test-account",iso(9),"session-one"),iso(9,30),1),buildFocusCompletionRecord(createFocusSession(2,"test-account",iso(10),"session-two"),iso(11,30),2)];return state;}
test("allocation is user declared and requires exactly 100 percent",()=>{assert.equal(validateAllocation(allocation),null);assert.ok(validateAllocation({...allocation,shares:[{categoryId:"goal:1",percent:99}]}));});
test("invalid, duplicate, extra-field, negative and oversized allocations fail",()=>{for(const shares of [[{categoryId:"goal:1",percent:-1}],[{categoryId:"goal:1",percent:100},{categoryId:"goal:1",percent:0}],[{categoryId:"goal:1",percent:100,approved:true}],[{categoryId:"wrong",percent:100}]]) assert.ok(validateAllocation({...allocation,shares}));assert.ok(validateAllocation({...allocation,approved:true}));});
test("planning hierarchy maps exact goal categories",()=>{const r=buildAttentionReport(measured(),allocation,now);assert.deepEqual(r.ledger.map(e=>e.categoryId),["goal:1","goal:2"]);assert.equal(r.totalMs,7_200_000);assert.equal(r.rows[0].actual,25);assert.equal(r.rows[1].actual,75);});
test("30/90 minute proof produces explainable 65 alignment",()=>assert.equal(buildAttentionReport(measured(),allocation,now).alignment,65));
test("exact distribution yields 100 alignment",()=>{const s=source();s.executionRecords=[focus(1,9,12),focus(2,13,15)];assert.equal(buildAttentionReport(s,allocation,now).alignment,100);});
test("divergence lowers alignment and score stays bounded",()=>{for(let a=0;a<=100;a+=10){const r=buildAttentionReport(measured(),{...allocation,shares:[{categoryId:"goal:1",percent:a},{categoryId:"goal:2",percent:100-a}]},now);assert.ok(r.alignment!>=0&&r.alignment!<=100);}assert.equal(buildAttentionReport(measured(),{...allocation,shares:[{categoryId:"goal:1",percent:25},{categoryId:"goal:2",percent:75}]},now).alignment,100);});
test("missing relationship falls back without AI category guessing",()=>{const s=measured();s.weeklyTargets=[];assert.ok(buildAttentionReport(s,allocation,now).ledger.every(e=>e.categoryId==="uncategorized"));});
test("deleted tasks and goals use Uncategorized",()=>{const s=measured();s.tasks=[];assert.equal(buildAttentionReport(s,allocation,now).rows.at(-1)?.actual,100);});
test("inactive goals invalidate saved allocation without redistribution",()=>{const s=measured();s.lifeGoals[0].completed=true;const r=buildAttentionReport(s,allocation,now);assert.ok(r.allocationError?.includes("no longer active"));assert.equal(r.alignment,null);assert.equal(r.ledger[0].categoryId,"uncategorized");});
test("goal renaming preserves category identity",()=>{const s=measured();s.lifeGoals[0].title="Renamed";const r=buildAttentionReport(s,allocation,now);assert.equal(r.rows[0].id,"goal:1");assert.equal(r.rows[0].label,"Renamed");assert.equal(r.alignment,65);});
test("calendar week is local Monday to Sunday including Sunday",()=>{for(const date of [new Date(2026,9,5),new Date(2026,9,11)]){const w=attentionWeek(date);assert.equal(w.weekStart,"2026-10-05");assert.equal(w.weekEnd,"2026-10-11");}});
test("next Monday focus is excluded",()=>{const s=source();const e=focus(1,9,10);e.createdAt=new Date(2026,9,12,10).toISOString();e.metadata={...e.metadata,startedAt:new Date(2026,9,12,9).toISOString(),endedAt:e.createdAt};s.executionRecords=[e];assert.equal(buildAttentionReport(s,allocation,now).totalMs,0);});
test("cross-week sessions are excluded rather than invented prorating",()=>{const s=source();const e=focus(1,9,10);e.metadata={...e.metadata,startedAt:new Date(2026,9,4,23).toISOString(),endedAt:iso(10)};e.createdAt=iso(10);s.executionRecords=[e];const r=buildAttentionReport(s,allocation,now);assert.equal(r.totalMs,0);assert.equal(r.excluded,1);});
test("duplicate audit rows count one session not canonical event IDs",()=>{const s=measured();s.executionRecords=[...s.executionRecords,{...s.executionRecords[0],id:999}];assert.equal(buildAttentionReport(s,allocation,now).totalMs,7_200_000);});
test("duplicate canonical execution IDs preserve independent sessions",()=>{const s=measured();s.executionRecords=s.executionRecords.map(e=>({...e,id:1}));assert.equal(buildAttentionReport(s,allocation,now).ledger.length,2);});
test("conflicting session duplicates and overlaps excluded",()=>{const s=source();s.executionRecords=[focus(1,9,11),focus(2,10,12)];assert.equal(buildAttentionReport(s,allocation,now).totalMs,0);s.executionRecords=[focus(1,9,10),{...focus(1,9,10),metadata:{...focus(1,9,10).metadata,durationMs:1}}];assert.equal(buildAttentionReport(s,allocation,now).totalMs,0);});
test("pause-adjusted duration used, not whole wall-clock",()=>{const s=source();const e=focus(1,9,11);e.metadata!.durationMs=3_600_000;s.executionRecords=[e];assert.equal(buildAttentionReport(s,allocation,now).totalMs,3_600_000);});
test("invalid duration, entity identity, and timestamps fail safely",()=>{for(const patch of [{durationMs:NaN},{durationMs:-1},{durationMs:4_000_000},{taskId:99},{startedAt:"invalid"}]){const s=source();const e=focus(1,9,10);e.metadata={...e.metadata,...patch};s.executionRecords=[e];assert.equal(buildAttentionReport(s,allocation,now).totalMs,0);}});
test("zero time and missing intentions never imply zero alignment",()=>{assert.equal(buildAttentionReport(source(),allocation,now).alignment,null);assert.equal(buildAttentionReport(measured(),null,now).alignment,null);});
test("coverage is descriptive and boundary-exact",()=>{assert.deepEqual([0,1,2,5,15,16].map(h=>trackingCoverage(h*3_600_000)),["None","Very limited","Limited","Moderate","Moderate","Stronger signal"]);});
test("top mismatch, over and under insights use measured gaps",()=>{const r=buildAttentionReport(measured(),allocation,now);assert.deepEqual(r.insights.map(i=>i.id),["top-mismatch","over","under"]);assert.ok(r.insights[1].text.includes("35.0"));});
test("under two hours produces no mirror insight",()=>{const s=source();s.executionRecords=[focus(1,9,10)];assert.deepEqual(buildAttentionReport(s,allocation,now).insights,[]);});
test("current allocation applies explicitly; no historical intentions invented",()=>{const s=measured();const r=buildAttentionReport(s,{...allocation,updatedAt:now.toISOString(),shares:[{categoryId:"goal:1",percent:25},{categoryId:"goal:2",percent:75}]},now);assert.equal(r.alignment,100);assert.ok(r.limitations[0].includes("Current intended"));});
test("scheduled Google events, task completions and XP do not count as focus",()=>{const s=source();s.executionRecords=[{...focus(1,9,10),type:"task_completed",xpAwarded:25}];assert.equal(buildAttentionReport(s,allocation,now).totalMs,0);const ui=readFileSync(new URL("../../src/insights/RealityMirror.tsx",import.meta.url),"utf8");assert.ok(!ui.includes("useGoogleCalendar"));});
test("derivation is deterministic, immutable, and XP unchanged",()=>{const s=measured();const before=structuredClone(s);assert.deepEqual(buildAttentionReport(s,allocation,now),buildAttentionReport(s,allocation,now));assert.deepEqual(s,before);assert.equal(s.executionRecords.reduce((sum,e)=>sum+e.xpAwarded,0),0);});
test("account-scoped intentions persist without writing canonical domains",()=>{const map=new Map<string,string>();const writes:string[]=[];const storage={getItem:(key:string)=>map.get(key)??null,setItem:(key:string,value:string)=>{writes.push(key);map.set(key,value);}};const a="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",b="bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb";assert.equal(readAttentionPreferences(storage,a),null);assert.equal(writes.length,0);saveAttentionPreferences(storage,a,allocation);assert.deepEqual(readAttentionPreferences(storage,a),allocation);assert.equal(readAttentionPreferences(storage,b),null);assert.deepEqual(writes,[attentionStorageKey(a)]);assert.throws(()=>saveAttentionPreferences(storage,"bad",allocation));});
test("malformed preferences are not rewritten",()=>{let writes=0;const storage={getItem:()=>"broken",setItem:()=>{writes++;}};assert.equal(readAttentionPreferences(storage,"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),null);assert.equal(writes,0);});
test("Reviews integration exposes labels, no mutation or hosted provider",()=>{const ui=readFileSync(new URL("../../src/insights/RealityMirror.tsx",import.meta.url),"utf8");assert.ok(ui.includes("key={identity.userId}"));assert.ok(ui.includes("aria-label"));for(const banned of ["appendConfirmed","completeTask","updateProfile","approveEvent","HostedAtlasProvider","updateHabit"])assert.ok(!ui.includes(banned));});
test("active categories include only incomplete goals and Uncategorized",()=>{const s=source();s.lifeGoals[0].completed=true;assert.deepEqual(attentionCategories(s).map(c=>c.id),["goal:2","uncategorized"]);});
